---
# tasks file for ntp
- name: include default variables
  include_vars: "../vars/main.yml"

- name: include release specific variables
  include_vars: "{{ _loop_var }}"
  loop: "{{ query('first_found', _params) }}"
  loop_control:
    loop_var: _loop_var
  vars:
    _params:
      files:
        - "{{ ansible_distribution | lower }}-{{ ansible_distribution_version | lower }}.yml"
        - "{{ ansible_distribution | lower }}-{{ ansible_distribution_major_version | lower }}.yml"
        - "{{ ansible_distribution | lower }}.yml"
        - "{{ ansible_os_family | lower }}-{{ ansible_distribution_version | lower }}.yml"
        - "{{ ansible_os_family | lower }}-{{ ansible_distribution_major_version | lower }}.yml"
        - "{{ ansible_os_family | lower }}.yml"
      paths:
        - "../vars"
      skip: true

- name: include release specific tasks
  include_tasks: "{{ _loop_var }}"
  loop: "{{ query('first_found', _params) }}"
  loop_control:
    loop_var: _loop_var
  vars:
    _params:
      files:
        - "{{ ansible_distribution | lower }}-{{ ansible_distribution_version | lower }}.yml"
        - "{{ ansible_distribution | lower }}-{{ ansible_distribution_major_version | lower }}.yml"
        - "{{ ansible_distribution | lower }}.yml"
        - "{{ ansible_os_family | lower }}-{{ ansible_distribution_version | lower }}.yml"
        - "{{ ansible_os_family | lower }}-{{ ansible_distribution_major_version | lower }}.yml"
        - "{{ ansible_os_family | lower }}.yml"
      paths:
        - "."
      skip: true

- name: remove lines in ntp.conf
  replace:
    path: /etc/ntp.conf
    regexp: '(^server)(.+)'
    replace: '#\1\2'
  tags:
    - remove_ntpconf

- name: add ntp servers to ntp.conf
  lineinfile:
    path: /etc/ntp.conf
    insertafter: '^#server'
    state: present
    line: |+
      restrict {{ ipsection }} mask {{ ipmask }} nomodify notrap
      server 127.127.1.0
      fudge 127.127.1.0 stratum 10
  when: inventory_hostname == ntpserver
  tags:
    - add_new_ntpconf

- name: add HW Sync
  lineinfile: 
    path: "/etc/sysconfig/ntpd"
    insertafter: EOF
    line: "SYNC_HWCLOCK=yes"
  when: inventory_hostname == ntpserver
  tags:
    - add_new_ntpd

- name: enable and start ntpd
  systemd:
    name: ntpd
    daemon_reload: yes
    state: started
    enabled: yes
  when: inventory_hostname == ntpserver
  tags:
    - enable_start_ntpd

- name: Control whether NTP is enabled
  shell: /usr/bin/timedatectl set-ntp yes
  tags:
    - enable_ntp_control

- name: Sync with the NTP server
  cron: 
    name: 'ntp sync' 
    minute: '*/2'
    hour: '*'
    day: '*'
    month: '*'
    weekday: '*'
    job: '/usr/sbin/ntpdate {{ ntpserver }} >/dev/null 2>&1;/sbin/hwclock -w'
  when: inventory_hostname != ntpserver
  tags:
    - sync_with_ntpserver
