---
dependency:
  name: galaxy
driver:
  name: delegated
  options:
    managed: false
    ansible_connection_options:
      ansible_connection: local
      ansible_python_interpreter: /usr/bin/python2.7
platforms:
  - name: instance
provisioner:
  name: ansible
  config_options:
    defaults:
      forks: 20
    ssh_connection:
      pipelining: true
      ssh_args: -o ControlMaster=auto -o ControlPersist=600s
verifier:
  name: ansible
