---
# This is an example playbook to execute Ansible tests.

- name: Verify
  hosts: all
  gather_facts: false
  tasks:
  - name: uname -a
    command: uname -a
    register: result
    changed_when: result is not succeeded
