---
# This is an example playbook to execute Ansible tests.

- name: Verify
  hosts: all
  remote_user: root
  become: true
  tasks:
    - name: check service status
      command: systemctl status {{ item.name }}
      register: result
      changed_when: result is not succeeded
      failed_when: "'inactive' not in result.stdout"
      loop: "{{service_todo}}"
